// SPDX-License-Identifier: Apache-2.0

/// \file ship_templates.cppm
/// \brief Immutable ship template definitions and lookup functions.

export module gb.entities:ship_templates;

import std;

import :ship_types;
import :types;

/// \brief Strongly-typed immutable specifications and capabilities for a ship
/// class.
export struct ShipTemplate {
  ShipType type{ShipType::STYPE_POD};
  std::string_view name;
  char letter{'p'};

  // Baseline capacities & numerical metrics
  double base_tech{0.0};       ///< Baseline technology requirement
  resource_t max_resource{0};  ///< Maximum resource cargo capacity
  hangar_t max_hangar{0};      ///< Maximum hangar capacity
  resource_t max_destruct{0};  ///< Maximum destruct crystal capacity
  gun_count_t max_guns{0};     ///< Number of gun mounts
  guntype_t max_primary_caliber{
      guntype_t::NONE};  ///< Maximum primary gun caliber
  guntype_t max_secondary_caliber{
      guntype_t::NONE};           ///< Maximum secondary gun caliber
  fuel_t max_fuel{0.0};           ///< Maximum fuel tank capacity
  population_t max_crew{0};       ///< Maximum crew accommodation capacity
  armor_t base_armor{0};          ///< Baseline hull armor rating
  resource_t build_cost{0};       ///< Base construction cost in resources
  speed_t base_speed{0};          ///< Base engine throttle speed rating
  damage_t base_damage{0};        ///< Base structural damage threshold
  double build_time{0.0};         ///< Construction build time factor
  double construction_cost{0.0};  ///< Construction cost multiplier
  bool can_modify{false};         ///< Can be customized / modified

  // Boolean capabilities & operational permissions
  bool can_mount_laser{false};  ///< Can be equipped with combat laser mount
  bool can_mount{false};        ///< Can mount warp crystals for hyperjump
  bool can_hyperjump{false};    ///< Equipped with hyperjump drive
  bool can_land{false};         ///< Capable of planetary landing
  bool has_switch{false};       ///< Has toggleable power/mode switch
  bool has_cew{false};          ///< Equipped with Concentrated Energy Weapon
  bool can_cloak{false};        ///< Equipped with cloaking device
  bool is_god_only{false};      ///< Restricted to deity/admin creation
  bool is_programmed{false};    ///< Autonomous / automated AI control
  bool is_starport{false};      ///< Operates as a starport
  bool can_repair{false};       ///< Capable of self/fleet repair
  bool requires_maintenance{
      false};  ///< Incurs regular economic maintenance cost

  /// \brief Indicates whether the ship class supports mounting a primary
  /// battery.
  [[nodiscard]] constexpr bool has_primary() const noexcept {
    return max_primary_caliber != guntype_t::NONE;
  }

  /// \brief Indicates whether the ship class supports mounting a secondary
  /// battery.
  [[nodiscard]] constexpr bool has_secondary() const noexcept {
    return max_secondary_caliber != guntype_t::NONE;
  }

  /// \brief Returns whether this ship type can be built on a planetary surface.
  [[nodiscard]] constexpr bool can_build_on_planet() const noexcept {
    return (static_cast<int>(build_time) & 1) != 0;
  }

  /// \brief Returns whether this ship type can be constructed by the specified
  /// builder ship template.
  [[nodiscard]] constexpr bool
  can_be_built_by(const ShipTemplate& builder) const noexcept {
    return (static_cast<int>(build_time) &
            static_cast<int>(builder.construction_cost)) != 0;
  }

  /// \brief Returns whether this ship type is equipped to construct other
  /// ships.
  [[nodiscard]] constexpr bool can_construct_ships() const noexcept {
    return static_cast<int>(construction_cost) != 0;
  }
};

export inline constexpr std::array<ShipTemplate, NUMSTYPES> ship_templates = {{
    // 0: STYPE_POD (Spore pod, 'p')
    {.type = ShipType::STYPE_POD,
     .name = "Spore pod",
     .letter = 'p',
     .base_tech = 0,
     .max_resource = 0,
     .max_hangar = 0,
     .max_destruct = 0,
     .max_guns = 0,
     .max_primary_caliber = guntype_t::NONE,
     .max_secondary_caliber = guntype_t::NONE,
     .max_fuel = 20,
     .max_crew = 1,
     .base_armor = 0,
     .build_cost = 1,
     .base_speed = 2,
     .base_damage = 0,
     .build_time = 1,
     .construction_cost = 0,
     .can_modify = false,
     .can_mount_laser = false,
     .can_mount = false,
     .can_hyperjump = false,
     .can_land = true,
     .has_switch = false,
     .has_cew = false,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = false,
     .can_repair = true,
     .requires_maintenance = false},

    // 1: STYPE_SHUTTLE (Shuttle, 's')
    {.type = ShipType::STYPE_SHUTTLE,
     .name = "Shuttle",
     .letter = 's',
     .base_tech = 10,
     .max_resource = 25,
     .max_hangar = 2,
     .max_destruct = 2,
     .max_guns = 1,
     .max_primary_caliber = guntype_t::LIGHT,
     .max_secondary_caliber = guntype_t::NONE,
     .max_fuel = 20,
     .max_crew = 10,
     .base_armor = 0,
     .build_cost = 2,
     .base_speed = 4,
     .base_damage = 0,
     .build_time = 8,
     .construction_cost = 4,
     .can_modify = true,
     .can_mount_laser = false,
     .can_mount = false,
     .can_hyperjump = false,
     .can_land = true,
     .has_switch = false,
     .has_cew = false,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = false,
     .can_repair = false,
     .requires_maintenance = true},

    // 2: STYPE_CARRIER (Carrier, 'X')
    {.type = ShipType::STYPE_CARRIER,
     .name = "Carrier",
     .letter = 'X',
     .base_tech = 250,
     .max_resource = 600,
     .max_hangar = 200,
     .max_destruct = 800,
     .max_guns = 30,
     .max_primary_caliber = guntype_t::HEAVY,
     .max_secondary_caliber = guntype_t::MEDIUM,
     .max_fuel = 1000,
     .max_crew = 30,
     .base_armor = 5,
     .build_cost = 30,
     .base_speed = 4,
     .base_damage = 50,
     .build_time = 20,
     .construction_cost = 2,
     .can_modify = true,
     .can_mount_laser = true,
     .can_mount = true,
     .can_hyperjump = true,
     .can_land = false,
     .has_switch = false,
     .has_cew = true,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = false,
     .can_repair = true,
     .requires_maintenance = true},

    // 3: STYPE_DREADNT (Dreadnaught, 'D')
    {.type = ShipType::STYPE_DREADNT,
     .name = "Dreadnaught",
     .letter = 'D',
     .base_tech = 300,
     .max_resource = 500,
     .max_hangar = 10,
     .max_destruct = 500,
     .max_guns = 60,
     .max_primary_caliber = guntype_t::HEAVY,
     .max_secondary_caliber = guntype_t::MEDIUM,
     .max_fuel = 500,
     .max_crew = 60,
     .base_armor = 10,
     .build_cost = 40,
     .base_speed = 6,
     .base_damage = 50,
     .build_time = 8,
     .construction_cost = 2,
     .can_modify = true,
     .can_mount_laser = true,
     .can_mount = true,
     .can_hyperjump = true,
     .can_land = true,
     .has_switch = false,
     .has_cew = true,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = false,
     .can_repair = false,
     .requires_maintenance = true},

    // 4: STYPE_BATTLE (Battleship, 'B')
    {.type = ShipType::STYPE_BATTLE,
     .name = "Battleship",
     .letter = 'B',
     .base_tech = 200,
     .max_resource = 235,
     .max_hangar = 10,
     .max_destruct = 400,
     .max_guns = 30,
     .max_primary_caliber = guntype_t::HEAVY,
     .max_secondary_caliber = guntype_t::MEDIUM,
     .max_fuel = 200,
     .max_crew = 30,
     .base_armor = 7,
     .build_cost = 20,
     .base_speed = 6,
     .base_damage = 50,
     .build_time = 8,
     .construction_cost = 2,
     .can_modify = true,
     .can_mount_laser = true,
     .can_mount = true,
     .can_hyperjump = true,
     .can_land = true,
     .has_switch = false,
     .has_cew = true,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = false,
     .can_repair = false,
     .requires_maintenance = true},

    // 5: STYPE_INTCPT (Interceptor, 'I')
    {.type = ShipType::STYPE_INTCPT,
     .name = "Interceptor",
     .letter = 'I',
     .base_tech = 150,
     .max_resource = 110,
     .max_hangar = 5,
     .max_destruct = 120,
     .max_guns = 20,
     .max_primary_caliber = guntype_t::MEDIUM,
     .max_secondary_caliber = guntype_t::MEDIUM,
     .max_fuel = 200,
     .max_crew = 20,
     .base_armor = 3,
     .build_cost = 15,
     .base_speed = 6,
     .base_damage = 50,
     .build_time = 8,
     .construction_cost = 2,
     .can_modify = true,
     .can_mount_laser = true,
     .can_mount = true,
     .can_hyperjump = true,
     .can_land = true,
     .has_switch = false,
     .has_cew = true,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = false,
     .can_repair = false,
     .requires_maintenance = true},

    // 6: STYPE_CRUISER (Cruiser, 'C')
    {.type = ShipType::STYPE_CRUISER,
     .name = "Cruiser",
     .letter = 'C',
     .base_tech = 150,
     .max_resource = 165,
     .max_hangar = 5,
     .max_destruct = 300,
     .max_guns = 20,
     .max_primary_caliber = guntype_t::HEAVY,
     .max_secondary_caliber = guntype_t::MEDIUM,
     .max_fuel = 120,
     .max_crew = 20,
     .base_armor = 5,
     .build_cost = 10,
     .base_speed = 6,
     .base_damage = 50,
     .build_time = 8,
     .construction_cost = 2,
     .can_modify = true,
     .can_mount_laser = true,
     .can_mount = true,
     .can_hyperjump = true,
     .can_land = true,
     .has_switch = false,
     .has_cew = true,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = false,
     .can_repair = false,
     .requires_maintenance = true},

    // 7: STYPE_DESTROYER (Destroyer, 'd')
    {.type = ShipType::STYPE_DESTROYER,
     .name = "Destroyer",
     .letter = 'd',
     .base_tech = 100,
     .max_resource = 110,
     .max_hangar = 5,
     .max_destruct = 120,
     .max_guns = 15,
     .max_primary_caliber = guntype_t::MEDIUM,
     .max_secondary_caliber = guntype_t::MEDIUM,
     .max_fuel = 80,
     .max_crew = 15,
     .base_armor = 3,
     .build_cost = 5,
     .base_speed = 6,
     .base_damage = 50,
     .build_time = 8,
     .construction_cost = 2,
     .can_modify = true,
     .can_mount_laser = true,
     .can_mount = true,
     .can_hyperjump = true,
     .can_land = true,
     .has_switch = false,
     .has_cew = true,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = false,
     .can_repair = false,
     .requires_maintenance = true},

    // 8: STYPE_FIGHTER (Fighter Group, 'f')
    {.type = ShipType::STYPE_FIGHTER,
     .name = "Fighter Group",
     .letter = 'f',
     .base_tech = 100,
     .max_resource = 0,
     .max_hangar = 0,
     .max_destruct = 40,
     .max_guns = 20,
     .max_primary_caliber = guntype_t::MEDIUM,
     .max_secondary_caliber = guntype_t::LIGHT,
     .max_fuel = 10,
     .max_crew = 1,
     .base_armor = 2,
     .build_cost = 1,
     .base_speed = 9,
     .base_damage = 0,
     .build_time = 8,
     .construction_cost = 2,
     .can_modify = true,
     .can_mount_laser = true,
     .can_mount = true,
     .can_hyperjump = true,
     .can_land = true,
     .has_switch = false,
     .has_cew = true,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = false,
     .can_repair = true,
     .requires_maintenance = true},

    // 9: STYPE_EXPLORER (Explorer, 'e')
    {.type = ShipType::STYPE_EXPLORER,
     .name = "Explorer",
     .letter = 'e',
     .base_tech = 40,
     .max_resource = 10,
     .max_hangar = 0,
     .max_destruct = 15,
     .max_guns = 5,
     .max_primary_caliber = guntype_t::MEDIUM,
     .max_secondary_caliber = guntype_t::NONE,
     .max_fuel = 35,
     .max_crew = 5,
     .base_armor = 1,
     .build_cost = 2,
     .base_speed = 6,
     .base_damage = 0,
     .build_time = 8,
     .construction_cost = 0,
     .can_modify = true,
     .can_mount_laser = true,
     .can_mount = true,
     .can_hyperjump = true,
     .can_land = true,
     .has_switch = false,
     .has_cew = false,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = false,
     .can_repair = false,
     .requires_maintenance = true},

    // 10: STYPE_HABITAT (Habitat, 'H')
    {.type = ShipType::STYPE_HABITAT,
     .name = "Habitat",
     .letter = 'H',
     .base_tech = 100,
     .max_resource = 5000,
     .max_hangar = 10,
     .max_destruct = 500,
     .max_guns = 20,
     .max_primary_caliber = guntype_t::MEDIUM,
     .max_secondary_caliber = guntype_t::LIGHT,
     .max_fuel = 2000,
     .max_crew = 2000,
     .base_armor = 3,
     .build_cost = 50,
     .base_speed = 4,
     .base_damage = 75,
     .build_time = 20,
     .construction_cost = 18,
     .can_modify = true,
     .can_mount_laser = false,
     .can_mount = false,
     .can_hyperjump = false,
     .can_land = false,
     .has_switch = true,
     .has_cew = false,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = true,
     .can_repair = true,
     .requires_maintenance = true},

    // 11: STYPE_STATION (Station, 'S')
    {.type = ShipType::STYPE_STATION,
     .name = "Station",
     .letter = 'S',
     .base_tech = 100,
     .max_resource = 5000,
     .max_hangar = 10,
     .max_destruct = 250,
     .max_guns = 20,
     .max_primary_caliber = guntype_t::MEDIUM,
     .max_secondary_caliber = guntype_t::NONE,
     .max_fuel = 2000,
     .max_crew = 50,
     .base_armor = 1,
     .build_cost = 10,
     .base_speed = 4,
     .base_damage = 75,
     .build_time = 20,
     .construction_cost = 6,
     .can_modify = true,
     .can_mount_laser = false,
     .can_mount = false,
     .can_hyperjump = false,
     .can_land = false,
     .has_switch = false,
     .has_cew = false,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = true,
     .can_repair = true,
     .requires_maintenance = true},

    // 12: STYPE_OAP (Ob Asst Pltfrm, 'O')
    {.type = ShipType::STYPE_OAP,
     .name = "Ob Asst Pltfrm",
     .letter = 'O',
     .base_tech = 200,
     .max_resource = 1400,
     .max_hangar = 20,
     .max_destruct = 1000,
     .max_guns = 50,
     .max_primary_caliber = guntype_t::HEAVY,
     .max_secondary_caliber = guntype_t::MEDIUM,
     .max_fuel = 2000,
     .max_crew = 200,
     .base_armor = 5,
     .build_cost = 40,
     .base_speed = 4,
     .base_damage = 75,
     .build_time = 20,
     .construction_cost = 6,
     .can_modify = true,
     .can_mount_laser = true,
     .can_mount = true,
     .can_hyperjump = true,
     .can_land = false,
     .has_switch = false,
     .has_cew = true,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = false,
     .can_repair = true,
     .requires_maintenance = true},

    // 13: STYPE_CARGO (Cargo Ship, 'c')
    {.type = ShipType::STYPE_CARGO,
     .name = "Cargo Ship",
     .letter = 'c',
     .base_tech = 100,
     .max_resource = 1000,
     .max_hangar = 5,
     .max_destruct = 1000,
     .max_guns = 10,
     .max_primary_caliber = guntype_t::LIGHT,
     .max_secondary_caliber = guntype_t::NONE,
     .max_fuel = 1000,
     .max_crew = 100,
     .base_armor = 2,
     .build_cost = 10,
     .base_speed = 4,
     .base_damage = 0,
     .build_time = 8,
     .construction_cost = 4,
     .can_modify = true,
     .can_mount_laser = false,
     .can_mount = true,
     .can_hyperjump = true,
     .can_land = true,
     .has_switch = false,
     .has_cew = false,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = false,
     .can_repair = false,
     .requires_maintenance = true},

    // 14: STYPE_TANKER (Tanker, 't')
    {.type = ShipType::STYPE_TANKER,
     .name = "Tanker",
     .letter = 't',
     .base_tech = 100,
     .max_resource = 200,
     .max_hangar = 5,
     .max_destruct = 200,
     .max_guns = 10,
     .max_primary_caliber = guntype_t::LIGHT,
     .max_secondary_caliber = guntype_t::NONE,
     .max_fuel = 5000,
     .max_crew = 10,
     .base_armor = 2,
     .build_cost = 10,
     .base_speed = 4,
     .base_damage = 0,
     .build_time = 8,
     .construction_cost = 2,
     .can_modify = true,
     .can_mount_laser = false,
     .can_mount = true,
     .can_hyperjump = true,
     .can_land = true,
     .has_switch = false,
     .has_cew = false,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = false,
     .can_repair = false,
     .requires_maintenance = true},

    // 15: STYPE_GOD (GODSHIP, '!')
    {.type = ShipType::STYPE_GOD,
     .name = "GODSHIP",
     .letter = '!',
     .base_tech = 9999,
     .max_resource = 20000,
     .max_hangar = 1000,
     .max_destruct = 20000,
     .max_guns = 1000,
     .max_primary_caliber = guntype_t::HEAVY,
     .max_secondary_caliber = guntype_t::HEAVY,
     .max_fuel = 20000,
     .max_crew = 1000,
     .base_armor = 100,
     .build_cost = 10,
     .base_speed = 9,
     .base_damage = 0,
     .build_time = 1,
     .construction_cost = 6,
     .can_modify = true,
     .can_mount_laser = true,
     .can_mount = true,
     .can_hyperjump = true,
     .can_land = true,
     .has_switch = false,
     .has_cew = true,
     .can_cloak = false,
     .is_god_only = true,
     .is_programmed = true,
     .is_starport = true,
     .can_repair = true,
     .requires_maintenance = false},

    // 16: STYPE_MINE (Space Mine, '+')
    {.type = ShipType::STYPE_MINE,
     .name = "Space Mine",
     .letter = '+',
     .base_tech = 50,
     .max_resource = 0,
     .max_hangar = 0,
     .max_destruct = 25,
     .max_guns = 0,
     .max_primary_caliber = guntype_t::NONE,
     .max_secondary_caliber = guntype_t::NONE,
     .max_fuel = 20,
     .max_crew = 0,
     .base_armor = 1,
     .build_cost = 30,
     .base_speed = 2,
     .base_damage = 0,
     .build_time = 8,
     .construction_cost = 0,
     .can_modify = true,
     .can_mount_laser = false,
     .can_mount = false,
     .can_hyperjump = false,
     .can_land = true,
     .has_switch = true,
     .has_cew = false,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = false,
     .can_repair = false,
     .requires_maintenance = false},

    // 17: STYPE_MIRROR (Space Mirror, 'M')
    {.type = ShipType::STYPE_MIRROR,
     .name = "Space Mirror",
     .letter = 'M',
     .base_tech = 100,
     .max_resource = 200,
     .max_hangar = 0,
     .max_destruct = 10,
     .max_guns = 1,
     .max_primary_caliber = guntype_t::LIGHT,
     .max_secondary_caliber = guntype_t::NONE,
     .max_fuel = 20,
     .max_crew = 5,
     .base_armor = 0,
     .build_cost = 100,
     .base_speed = 2,
     .base_damage = 75,
     .build_time = 20,
     .construction_cost = 0,
     .can_modify = false,
     .can_mount_laser = false,
     .can_mount = false,
     .can_hyperjump = false,
     .can_land = false,
     .has_switch = false,
     .has_cew = false,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = false,
     .can_repair = true,
     .requires_maintenance = true},

    // 18: OTYPE_STELE (Space Telescope, '=')
    {.type = ShipType::OTYPE_STELE,
     .name = "Space Telescope",
     .letter = '=',
     .base_tech = 50,
     .max_resource = 0,
     .max_hangar = 0,
     .max_destruct = 0,
     .max_guns = 0,
     .max_primary_caliber = guntype_t::NONE,
     .max_secondary_caliber = guntype_t::NONE,
     .max_fuel = 20,
     .max_crew = 2,
     .base_armor = 0,
     .build_cost = 20,
     .base_speed = 4,
     .base_damage = 0,
     .build_time = 8,
     .construction_cost = 0,
     .can_modify = true,
     .can_mount_laser = false,
     .can_mount = true,
     .can_hyperjump = true,
     .can_land = true,
     .has_switch = false,
     .has_cew = false,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = false,
     .can_repair = false,
     .requires_maintenance = true},

    // 19: OTYPE_GTELE (Ground Telescope, '\')
    {.type = ShipType::OTYPE_GTELE,
     .name = "Ground Telescope",
     .letter = '\\',
     .base_tech = 5,
     .max_resource = 0,
     .max_hangar = 0,
     .max_destruct = 0,
     .max_guns = 0,
     .max_primary_caliber = guntype_t::NONE,
     .max_secondary_caliber = guntype_t::NONE,
     .max_fuel = 0,
     .max_crew = 2,
     .base_armor = 0,
     .build_cost = 2,
     .base_speed = 0,
     .base_damage = 0,
     .build_time = 1,
     .construction_cost = 0,
     .can_modify = false,
     .can_mount_laser = false,
     .can_mount = false,
     .can_hyperjump = false,
     .can_land = true,
     .has_switch = false,
     .has_cew = false,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = false,
     .can_repair = true,
     .requires_maintenance = false},

    // 20: OTYPE_TRACT (* T-R beam, '-')
    {.type = ShipType::OTYPE_TRACT,
     .name = "* T-R beam",
     .letter = '-',
     .base_tech = 200,
     .max_resource = 0,
     .max_hangar = 0,
     .max_destruct = 0,
     .max_guns = 0,
     .max_primary_caliber = guntype_t::NONE,
     .max_secondary_caliber = guntype_t::NONE,
     .max_fuel = 1000,
     .max_crew = 5,
     .base_armor = 0,
     .build_cost = 20,
     .base_speed = 2,
     .base_damage = 0,
     .build_time = 1,
     .construction_cost = 0,
     .can_modify = false,
     .can_mount_laser = false,
     .can_mount = true,
     .can_hyperjump = false,
     .can_land = true,
     .has_switch = true,
     .has_cew = false,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = false,
     .is_starport = false,
     .can_repair = true,
     .requires_maintenance = false},

    // 21: OTYPE_AP (Atmosph Processor, 'a')
    {.type = ShipType::OTYPE_AP,
     .name = "Atmosph Processor",
     .letter = 'a',
     .base_tech = 80,
     .max_resource = 0,
     .max_hangar = 0,
     .max_destruct = 0,
     .max_guns = 0,
     .max_primary_caliber = guntype_t::NONE,
     .max_secondary_caliber = guntype_t::NONE,
     .max_fuel = 200,
     .max_crew = 10,
     .base_armor = 1,
     .build_cost = 20,
     .base_speed = 0,
     .base_damage = 0,
     .build_time = 1,
     .construction_cost = 0,
     .can_modify = false,
     .can_mount_laser = false,
     .can_mount = false,
     .can_hyperjump = false,
     .can_land = true,
     .has_switch = true,
     .has_cew = false,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = false,
     .can_repair = true,
     .requires_maintenance = false},

    // 22: OTYPE_CANIST (Dust Canister, 'g')
    {.type = ShipType::OTYPE_CANIST,
     .name = "Dust Canister",
     .letter = 'g',
     .base_tech = 40,
     .max_resource = 0,
     .max_hangar = 0,
     .max_destruct = 0,
     .max_guns = 0,
     .max_primary_caliber = guntype_t::NONE,
     .max_secondary_caliber = guntype_t::NONE,
     .max_fuel = 1,
     .max_crew = 0,
     .base_armor = 0,
     .build_cost = 10,
     .base_speed = 1,
     .base_damage = 0,
     .build_time = 1,
     .construction_cost = 0,
     .can_modify = false,
     .can_mount_laser = false,
     .can_mount = false,
     .can_hyperjump = false,
     .can_land = true,
     .has_switch = true,
     .has_cew = false,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = false,
     .can_repair = true,
     .requires_maintenance = false},

    // 23: OTYPE_GREEN (Greenhouse Gases, 'h')
    {.type = ShipType::OTYPE_GREEN,
     .name = "Greenhouse Gases",
     .letter = 'h',
     .base_tech = 40,
     .max_resource = 0,
     .max_hangar = 0,
     .max_destruct = 0,
     .max_guns = 0,
     .max_primary_caliber = guntype_t::NONE,
     .max_secondary_caliber = guntype_t::NONE,
     .max_fuel = 1,
     .max_crew = 0,
     .base_armor = 0,
     .build_cost = 10,
     .base_speed = 1,
     .base_damage = 0,
     .build_time = 1,
     .construction_cost = 0,
     .can_modify = false,
     .can_mount_laser = false,
     .can_mount = false,
     .can_hyperjump = false,
     .can_land = true,
     .has_switch = false,
     .has_cew = false,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = false,
     .can_repair = true,
     .requires_maintenance = false},

    // 24: OTYPE_VN (V.Neumann Machine, 'v')
    {.type = ShipType::OTYPE_VN,
     .name = "V.Neumann Machine",
     .letter = 'v',
     .base_tech = 80,
     .max_resource = 20,
     .max_hangar = 0,
     .max_destruct = 0,
     .max_guns = 0,
     .max_primary_caliber = guntype_t::NONE,
     .max_secondary_caliber = guntype_t::NONE,
     .max_fuel = 50,
     .max_crew = 0,
     .base_armor = 1,
     .build_cost = 100,
     .base_speed = 4,
     .base_damage = 0,
     .build_time = 1,
     .construction_cost = 0,
     .can_modify = false,
     .can_mount_laser = false,
     .can_mount = false,
     .can_hyperjump = false,
     .can_land = true,
     .has_switch = false,
     .has_cew = false,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = false,
     .can_repair = false,
     .requires_maintenance = false},

    // 25: OTYPE_BERS (Berserker, 'V')
    {.type = ShipType::OTYPE_BERS,
     .name = "Berserker",
     .letter = 'V',
     .base_tech = 999,
     .max_resource = 50,
     .max_hangar = 0,
     .max_destruct = 500,
     .max_guns = 40,
     .max_primary_caliber = guntype_t::HEAVY,
     .max_secondary_caliber = guntype_t::MEDIUM,
     .max_fuel = 1000,
     .max_crew = 0,
     .base_armor = 15,
     .build_cost = 100,
     .base_speed = 6,
     .base_damage = 0,
     .build_time = 1,
     .construction_cost = 0,
     .can_modify = false,
     .can_mount_laser = false,
     .can_mount = false,
     .can_hyperjump = false,
     .can_land = true,
     .has_switch = true,
     .has_cew = false,
     .can_cloak = false,
     .is_god_only = true,
     .is_programmed = true,
     .is_starport = false,
     .can_repair = true,
     .requires_maintenance = false},

    // 26: OTYPE_GOV (Govrnmnt. Center, '@')
    {.type = ShipType::OTYPE_GOV,
     .name = "Govrnmnt. Center",
     .letter = '@',
     .base_tech = 0,
     .max_resource = 500,
     .max_hangar = 0,
     .max_destruct = 100,
     .max_guns = 10,
     .max_primary_caliber = guntype_t::LIGHT,
     .max_secondary_caliber = guntype_t::NONE,
     .max_fuel = 1000,
     .max_crew = 10,
     .base_armor = 20,
     .build_cost = 500,
     .base_speed = 0,
     .base_damage = 75,
     .build_time = 17,
     .construction_cost = 0,
     .can_modify = false,
     .can_mount_laser = false,
     .can_mount = false,
     .can_hyperjump = false,
     .can_land = true,
     .has_switch = false,
     .has_cew = false,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = true,
     .can_repair = true,
     .requires_maintenance = false},

    // 27: OTYPE_OMCL (Mind Control Lsr, 'l')
    {.type = ShipType::OTYPE_OMCL,
     .name = "Mind Control Lsr",
     .letter = 'l',
     .base_tech = 350,
     .max_resource = 25,
     .max_hangar = 0,
     .max_destruct = 0,
     .max_guns = 0,
     .max_primary_caliber = guntype_t::NONE,
     .max_secondary_caliber = guntype_t::NONE,
     .max_fuel = 100,
     .max_crew = 2,
     .base_armor = 1,
     .build_cost = 50,
     .base_speed = 4,
     .base_damage = 0,
     .build_time = 17,
     .construction_cost = 0,
     .can_modify = false,
     .can_mount_laser = false,
     .can_mount = false,
     .can_hyperjump = false,
     .can_land = true,
     .has_switch = true,
     .has_cew = false,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = false,
     .is_starport = false,
     .can_repair = false,
     .requires_maintenance = false},

    // 28: OTYPE_TOXWC (Tox Waste Canistr, 'w')
    {.type = ShipType::OTYPE_TOXWC,
     .name = "Tox Waste Canistr",
     .letter = 'w',
     .base_tech = 0,
     .max_resource = 0,
     .max_hangar = 0,
     .max_destruct = 0,
     .max_guns = 0,
     .max_primary_caliber = guntype_t::NONE,
     .max_secondary_caliber = guntype_t::NONE,
     .max_fuel = 20,
     .max_crew = 0,
     .base_armor = 0,
     .build_cost = 5,
     .base_speed = 4,
     .base_damage = 0,
     .build_time = 1,
     .construction_cost = 0,
     .can_modify = false,
     .can_mount_laser = false,
     .can_mount = false,
     .can_hyperjump = false,
     .can_land = true,
     .has_switch = false,
     .has_cew = false,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = false,
     .can_repair = false,
     .requires_maintenance = false},

    // 29: OTYPE_PROBE (Space Probe, ':')
    {.type = ShipType::OTYPE_PROBE,
     .name = "Space Probe",
     .letter = ':',
     .base_tech = 150,
     .max_resource = 0,
     .max_hangar = 0,
     .max_destruct = 0,
     .max_guns = 0,
     .max_primary_caliber = guntype_t::NONE,
     .max_secondary_caliber = guntype_t::NONE,
     .max_fuel = 20,
     .max_crew = 0,
     .base_armor = 0,
     .build_cost = 10,
     .base_speed = 9,
     .base_damage = 0,
     .build_time = 19,
     .construction_cost = 0,
     .can_modify = false,
     .can_mount_laser = false,
     .can_mount = false,
     .can_hyperjump = false,
     .can_land = true,
     .has_switch = false,
     .has_cew = false,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = false,
     .can_repair = false,
     .requires_maintenance = false},

    // 30: OTYPE_GR (Gamma Ray Laser, 'G')
    {.type = ShipType::OTYPE_GR,
     .name = "Gamma Ray Laser",
     .letter = 'G',
     .base_tech = 100,
     .max_resource = 50,
     .max_hangar = 0,
     .max_destruct = 120,
     .max_guns = 20,
     .max_primary_caliber = guntype_t::LIGHT,
     .max_secondary_caliber = guntype_t::NONE,
     .max_fuel = 0,
     .max_crew = 40,
     .base_armor = 3,
     .build_cost = 30,
     .base_speed = 0,
     .base_damage = 75,
     .build_time = 1,
     .construction_cost = 0,
     .can_modify = true,
     .can_mount_laser = false,
     .can_mount = false,
     .can_hyperjump = false,
     .can_land = true,
     .has_switch = true,
     .has_cew = true,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = false,
     .can_repair = true,
     .requires_maintenance = true},

    // 31: OTYPE_FACTORY (Factory, 'F')
    {.type = ShipType::OTYPE_FACTORY,
     .name = "Factory",
     .letter = 'F',
     .base_tech = 0,
     .max_resource = 50,
     .max_hangar = 0,
     .max_destruct = 0,
     .max_guns = 0,
     .max_primary_caliber = guntype_t::NONE,
     .max_secondary_caliber = guntype_t::NONE,
     .max_fuel = 0,
     .max_crew = 20,
     .base_armor = 0,
     .build_cost = 20,
     .base_speed = 0,
     .base_damage = 75,
     .build_time = 17,
     .construction_cost = 8,
     .can_modify = false,
     .can_mount_laser = false,
     .can_mount = false,
     .can_hyperjump = false,
     .can_land = true,
     .has_switch = true,
     .has_cew = false,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = false,
     .can_repair = true,
     .requires_maintenance = true},

    // 32: OTYPE_TERRA (Terraform Device, 'T')
    {.type = ShipType::OTYPE_TERRA,
     .name = "Terraform Device",
     .letter = 'T',
     .base_tech = 50,
     .max_resource = 40,
     .max_hangar = 5,
     .max_destruct = 0,
     .max_guns = 0,
     .max_primary_caliber = guntype_t::NONE,
     .max_secondary_caliber = guntype_t::NONE,
     .max_fuel = 200,
     .max_crew = 20,
     .base_armor = 1,
     .build_cost = 20,
     .base_speed = 4,
     .base_damage = 0,
     .build_time = 17,
     .construction_cost = 0,
     .can_modify = true,
     .can_mount_laser = false,
     .can_mount = true,
     .can_hyperjump = true,
     .can_land = true,
     .has_switch = true,
     .has_cew = false,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = false,
     .can_repair = true,
     .requires_maintenance = true},

    // 33: OTYPE_BERSCTLC (Bers Cntrl Center, ';')
    {.type = ShipType::OTYPE_BERSCTLC,
     .name = "Bers Cntrl Center",
     .letter = ';',
     .base_tech = 9999,
     .max_resource = 200,
     .max_hangar = 0,
     .max_destruct = 50,
     .max_guns = 0,
     .max_primary_caliber = guntype_t::HEAVY,
     .max_secondary_caliber = guntype_t::NONE,
     .max_fuel = 0,
     .max_crew = 0,
     .base_armor = 10,
     .build_cost = 3,
     .base_speed = 0,
     .base_damage = 0,
     .build_time = 1,
     .construction_cost = 0,
     .can_modify = false,
     .can_mount_laser = false,
     .can_mount = false,
     .can_hyperjump = false,
     .can_land = true,
     .has_switch = true,
     .has_cew = false,
     .can_cloak = false,
     .is_god_only = true,
     .is_programmed = false,
     .is_starport = false,
     .can_repair = true,
     .requires_maintenance = false},

    // 34: OTYPE_AUTOFAC (Bers Autofac, 'Z')
    {.type = ShipType::OTYPE_AUTOFAC,
     .name = "Bers Autofac",
     .letter = 'Z',
     .base_tech = 9999,
     .max_resource = 1000,
     .max_hangar = 0,
     .max_destruct = 1000,
     .max_guns = 0,
     .max_primary_caliber = guntype_t::NONE,
     .max_secondary_caliber = guntype_t::NONE,
     .max_fuel = 1000,
     .max_crew = 0,
     .base_armor = 10,
     .build_cost = 8,
     .base_speed = 0,
     .base_damage = 0,
     .build_time = 1,
     .construction_cost = 0,
     .can_modify = false,
     .can_mount_laser = false,
     .can_mount = false,
     .can_hyperjump = false,
     .can_land = true,
     .has_switch = true,
     .has_cew = false,
     .can_cloak = false,
     .is_god_only = true,
     .is_programmed = false,
     .is_starport = false,
     .can_repair = true,
     .requires_maintenance = false},

    // 35: OTYPE_TRANSDEV (AVPM Transporter, '[')
    {.type = ShipType::OTYPE_TRANSDEV,
     .name = "AVPM Transporter",
     .letter = '[',
     .base_tech = 200,
     .max_resource = 1000,
     .max_hangar = 0,
     .max_destruct = 1000,
     .max_guns = 0,
     .max_primary_caliber = guntype_t::NONE,
     .max_secondary_caliber = guntype_t::NONE,
     .max_fuel = 1000,
     .max_crew = 100,
     .base_armor = 0,
     .build_cost = 300,
     .base_speed = 0,
     .base_damage = 50,
     .build_time = 1,
     .construction_cost = 0,
     .can_modify = false,
     .can_mount_laser = false,
     .can_mount = false,
     .can_hyperjump = false,
     .can_land = true,
     .has_switch = true,
     .has_cew = false,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = false,
     .can_repair = true,
     .requires_maintenance = false},

    // 36: STYPE_MISSILE (Missile, '^')
    {.type = ShipType::STYPE_MISSILE,
     .name = "Missile",
     .letter = '^',
     .base_tech = 50,
     .max_resource = 0,
     .max_hangar = 0,
     .max_destruct = 10,
     .max_guns = 0,
     .max_primary_caliber = guntype_t::NONE,
     .max_secondary_caliber = guntype_t::NONE,
     .max_fuel = 5,
     .max_crew = 0,
     .base_armor = 0,
     .build_cost = 5,
     .base_speed = 6,
     .base_damage = 0,
     .build_time = 8,
     .construction_cost = 0,
     .can_modify = true,
     .can_mount_laser = false,
     .can_mount = false,
     .can_hyperjump = false,
     .can_land = false,
     .has_switch = true,
     .has_cew = false,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = false,
     .can_repair = false,
     .requires_maintenance = false},

    // 37: OTYPE_PLANDEF (Planet Def Net, 'P')
    {.type = ShipType::OTYPE_PLANDEF,
     .name = "Planet Def Net",
     .letter = 'P',
     .base_tech = 200,
     .max_resource = 50,
     .max_hangar = 0,
     .max_destruct = 500,
     .max_guns = 20,
     .max_primary_caliber = guntype_t::HEAVY,
     .max_secondary_caliber = guntype_t::NONE,
     .max_fuel = 0,
     .max_crew = 50,
     .base_armor = 10,
     .build_cost = 100,
     .base_speed = 0,
     .base_damage = 75,
     .build_time = 1,
     .construction_cost = 0,
     .can_modify = true,
     .can_mount_laser = false,
     .can_mount = false,
     .can_hyperjump = false,
     .can_land = true,
     .has_switch = true,
     .has_cew = false,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = false,
     .can_repair = true,
     .requires_maintenance = true},

    // 38: OTYPE_QUARRY (Quarry, 'q')
    {.type = ShipType::OTYPE_QUARRY,
     .name = "Quarry",
     .letter = 'q',
     .base_tech = 0,
     .max_resource = 0,
     .max_hangar = 0,
     .max_destruct = 0,
     .max_guns = 0,
     .max_primary_caliber = guntype_t::NONE,
     .max_secondary_caliber = guntype_t::NONE,
     .max_fuel = 200,
     .max_crew = 50,
     .base_armor = 1,
     .build_cost = 10,
     .base_speed = 0,
     .base_damage = 0,
     .build_time = 1,
     .construction_cost = 0,
     .can_modify = true,
     .can_mount_laser = false,
     .can_mount = false,
     .can_hyperjump = false,
     .can_land = true,
     .has_switch = true,
     .has_cew = false,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = false,
     .can_repair = true,
     .requires_maintenance = true},

    // 39: OTYPE_PLOW (Space Plow, 'K')
    {.type = ShipType::OTYPE_PLOW,
     .name = "Space Plow",
     .letter = 'K',
     .base_tech = 5,
     .max_resource = 0,
     .max_hangar = 0,
     .max_destruct = 0,
     .max_guns = 0,
     .max_primary_caliber = guntype_t::NONE,
     .max_secondary_caliber = guntype_t::NONE,
     .max_fuel = 200,
     .max_crew = 10,
     .base_armor = 1,
     .build_cost = 10,
     .base_speed = 0,
     .base_damage = 0,
     .build_time = 1,
     .construction_cost = 0,
     .can_modify = true,
     .can_mount_laser = false,
     .can_mount = false,
     .can_hyperjump = false,
     .can_land = true,
     .has_switch = true,
     .has_cew = false,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = false,
     .can_repair = false,
     .requires_maintenance = false},

    // 40: OTYPE_DOME (Dome, 'Y')
    {.type = ShipType::OTYPE_DOME,
     .name = "Dome",
     .letter = 'Y',
     .base_tech = 10,
     .max_resource = 100,
     .max_hangar = 0,
     .max_destruct = 0,
     .max_guns = 0,
     .max_primary_caliber = guntype_t::NONE,
     .max_secondary_caliber = guntype_t::NONE,
     .max_fuel = 0,
     .max_crew = 20,
     .base_armor = 1,
     .build_cost = 10,
     .base_speed = 0,
     .base_damage = 0,
     .build_time = 1,
     .construction_cost = 0,
     .can_modify = true,
     .can_mount_laser = false,
     .can_mount = false,
     .can_hyperjump = false,
     .can_land = true,
     .has_switch = true,
     .has_cew = false,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = false,
     .can_repair = true,
     .requires_maintenance = false},

    // 41: OTYPE_WPLANT (Weapons Plant, 'W')
    {.type = ShipType::OTYPE_WPLANT,
     .name = "Weapons Plant",
     .letter = 'W',
     .base_tech = 0,
     .max_resource = 500,
     .max_hangar = 0,
     .max_destruct = 0,
     .max_guns = 0,
     .max_primary_caliber = guntype_t::NONE,
     .max_secondary_caliber = guntype_t::NONE,
     .max_fuel = 500,
     .max_crew = 20,
     .base_armor = 5,
     .build_cost = 20,
     .base_speed = 0,
     .base_damage = 75,
     .build_time = 17,
     .construction_cost = 0,
     .can_modify = false,
     .can_mount_laser = false,
     .can_mount = false,
     .can_hyperjump = false,
     .can_land = true,
     .has_switch = false,
     .has_cew = false,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = false,
     .can_repair = true,
     .requires_maintenance = false},

    // 42: OTYPE_PORT (Space Port, 'J')
    {.type = ShipType::OTYPE_PORT,
     .name = "Space Port",
     .letter = 'J',
     .base_tech = 0,
     .max_resource = 0,
     .max_hangar = 0,
     .max_destruct = 0,
     .max_guns = 0,
     .max_primary_caliber = guntype_t::NONE,
     .max_secondary_caliber = guntype_t::NONE,
     .max_fuel = 0,
     .max_crew = 100,
     .base_armor = 3,
     .build_cost = 50,
     .base_speed = 0,
     .base_damage = 75,
     .build_time = 1,
     .construction_cost = 0,
     .can_modify = true,
     .can_mount_laser = false,
     .can_mount = false,
     .can_hyperjump = false,
     .can_land = true,
     .has_switch = false,
     .has_cew = false,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = true,
     .can_repair = true,
     .requires_maintenance = true},

    // 43: OTYPE_ABM (ABM Battery, '&')
    {.type = ShipType::OTYPE_ABM,
     .name = "ABM Battery",
     .letter = '&',
     .base_tech = 100,
     .max_resource = 5,
     .max_hangar = 0,
     .max_destruct = 50,
     .max_guns = 5,
     .max_primary_caliber = guntype_t::LIGHT,
     .max_secondary_caliber = guntype_t::NONE,
     .max_fuel = 0,
     .max_crew = 5,
     .base_armor = 5,
     .build_cost = 50,
     .base_speed = 0,
     .base_damage = 50,
     .build_time = 1,
     .construction_cost = 0,
     .can_modify = true,
     .can_mount_laser = false,
     .can_mount = false,
     .can_hyperjump = false,
     .can_land = true,
     .has_switch = true,
     .has_cew = false,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = false,
     .can_repair = true,
     .requires_maintenance = true},

    // 44: OTYPE_AFV (Mech, 'R')
    {.type = ShipType::OTYPE_AFV,
     .name = "Mech",
     .letter = 'R',
     .base_tech = 50,
     .max_resource = 5,
     .max_hangar = 0,
     .max_destruct = 20,
     .max_guns = 2,
     .max_primary_caliber = guntype_t::LIGHT,
     .max_secondary_caliber = guntype_t::NONE,
     .max_fuel = 20,
     .max_crew = 1,
     .base_armor = 2,
     .build_cost = 20,
     .base_speed = 0,
     .base_damage = 0,
     .build_time = 8,
     .construction_cost = 0,
     .can_modify = true,
     .can_mount_laser = false,
     .can_mount = false,
     .can_hyperjump = false,
     .can_land = false,
     .has_switch = false,
     .has_cew = false,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = false,
     .can_repair = true,
     .requires_maintenance = true},

    // 45: OTYPE_BUNKER (Bunker, 'b')
    {.type = ShipType::OTYPE_BUNKER,
     .name = "Bunker",
     .letter = 'b',
     .base_tech = 10,
     .max_resource = 100,
     .max_hangar = 20,
     .max_destruct = 100,
     .max_guns = 0,
     .max_primary_caliber = guntype_t::NONE,
     .max_secondary_caliber = guntype_t::NONE,
     .max_fuel = 100,
     .max_crew = 100,
     .base_armor = 15,
     .build_cost = 100,
     .base_speed = 0,
     .base_damage = 50,
     .build_time = 1,
     .construction_cost = 0,
     .can_modify = true,
     .can_mount_laser = false,
     .can_mount = false,
     .can_hyperjump = false,
     .can_land = false,
     .has_switch = false,
     .has_cew = false,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = false,
     .can_repair = true,
     .requires_maintenance = true},

    // 46: STYPE_LANDER (Lander, 'L')
    {.type = ShipType::STYPE_LANDER,
     .name = "Lander",
     .letter = 'L',
     .base_tech = 150,
     .max_resource = 100,
     .max_hangar = 10,
     .max_destruct = 200,
     .max_guns = 10,
     .max_primary_caliber = guntype_t::HEAVY,
     .max_secondary_caliber = guntype_t::NONE,
     .max_fuel = 100,
     .max_crew = 500,
     .base_armor = 7,
     .build_cost = 50,
     .base_speed = 2,
     .base_damage = 50,
     .build_time = 8,
     .construction_cost = 0,
     .can_modify = true,
     .can_mount_laser = false,
     .can_mount = true,
     .can_hyperjump = true,
     .can_land = true,
     .has_switch = false,
     .has_cew = false,
     .can_cloak = false,
     .is_god_only = false,
     .is_programmed = true,
     .is_starport = false,
     .can_repair = true,
     .requires_maintenance = true},
}};

/// \brief Returns immutable template specifications for a given ship class.
export [[nodiscard]] constexpr const ShipTemplate&
ship_template(ShipType type) noexcept {
  const auto idx = static_cast<std::size_t>(type);
  if (idx < ship_templates.size()) {
    return ship_templates[idx];
  }
  return ship_templates[0];
}

/// \brief Returns an array containing the classification letters of all ship
/// types.
export [[nodiscard]] constexpr std::array<char, NUMSTYPES>
get_all_ship_letters() noexcept {
  std::array<char, NUMSTYPES> letters{};
  for (std::size_t i = 0; i < NUMSTYPES; ++i) {
    letters[i] = ship_templates[i].letter;
  }
  return letters;
}

/// \brief Returns whether the given character corresponds to a known ship
/// classification letter.
export [[nodiscard]] constexpr bool is_valid_ship_letter(char c) noexcept {
  return std::ranges::any_of(
      ship_templates, [c](const ShipTemplate& t) { return t.letter == c; });
}

/// \brief Type-safe accessor for primary gun caliber from ShipTemplate.
/// \param ship_type The ship type to query.
/// \return Primary gun caliber as guntype_t.
export [[nodiscard]] constexpr guntype_t
shipdata_primary(ShipType ship_type) noexcept {
  return ship_template(ship_type).max_primary_caliber;
}

/// \brief Type-safe accessor for secondary gun caliber from ShipTemplate.
/// \param ship_type The ship type to query.
/// \return Secondary gun caliber as guntype_t.
export [[nodiscard]] constexpr guntype_t
shipdata_secondary(ShipType ship_type) noexcept {
  return ship_template(ship_type).max_secondary_caliber;
}

export double complexity(ShipType);  // Complexity for default ship of this type

/// Check if ship type appears in filter string
/// \param type Ship type to check
/// \param filter String containing ship type letters to match
/// \return True if ship type letter appears in filter string
export inline bool listed(ShipType type, std::string_view filter) {
  return std::ranges::any_of(
      filter, [type](char c) { return ship_template(type).letter == c; });
}
